In [1]:
import pandas as pd
import numpy as np

In [2]:
local = pd.read_csv(r"D:\Precipitation\local.cvs")
local

      point  latitude  longitude
0         0      42.2       -8.2
1         1      42.1       -8.6
2         2      42.1       -8.5
3         3      42.1       -8.4
4         4      42.1       -8.3
...     ...       ...        ...
1007   1058      37.1       -7.8
1008   1059      37.1       -7.7
1009   1062      37.0       -8.0
1010   1063      37.0       -7.9
1011   1064      37.0       -7.8

[1012 rows x 3 columns]

In [3]:
precip = pd.read_excel(r"C:\Users\joaoa\Desktop\Doutoramento\Daily_rainfall_analysis\ERA5_Rainfall_PT_mm_Oct1981_Sep2023.xlsx")
precip

,Index,P0000,P0001,P0002,P0003,P0004,P0005,P0006,P0007,P0008,...,P1047,P1048,P1055,P1056,P1057,P1058,P1059,P1062,P1063,P1064
0,1981-10-01,18.59,29.60,28.42,25.24,21.88,19.20,17.59,28.02,30.83,...,0.44,0.51,0.25,0.24,0.25,0.26,0.27,0.15,0.15,0.14
1,1981-10-02,3.65,9.55,8.22,6.58,4.94,3.69,2.98,10.32,9.63,...,0.02,0.02,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
2,1981-10-03,7.53,15.72,14.61,12.94,11.11,9.19,7.73,15.97,16.74,...,2.12,2.66,1.65,1.61,1.32,0.93,0.59,1.18,0.99,0.83
3,1981-10-04,51.39,47.14,49.84,52.24,54.10,53.28,50.52,45.37,48.99,...,0.29,0.47,0.53,0.49,0.43,0.35,0.28,0.25,0.24,0.22
4,1981-10-05,51.86,30.62,38.98,48.55,57.39,62.94,66.47,28.54,35.65,...,9.71,10.47,13.67,13.27,12.35,11.22,10.13,10.34,9.65,9.08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15325,2023-09-26,0.05,0.03,0.02,0.02,0.02,0.02,0.02,0.01,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
15326,2023-09-27,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
15327,2023-09-28,0.06,0.50,0.38,0.24,0.10,0.03,0.01,0.47,0.45,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
15328,2023-09-29,0.06,0.01,0.02,0.03,0.05,0.05,0.04,0.01,0.01,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
15329,2023-09-30,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00

In [7]:
max_diff = 0
n_errors = 0
prev_year = -1

for row in range(0, len(precip)): # range(0, len(precip))
    year = row//365 + 1981
    day = row - (row//365)*365 # Between 0 and 364
    
    if prev_year != year:
        df = pd.read_csv(r"D:\Precipitation\water_year\era5land_total_precipitation_" + str(year) + "_" + str(year+1) + "_(mm).csv", compression = "zip")
        print("Started water year " + str(year) + "_" + str(year+1))
    
    prev_year = year
    
    for col in range(1,1013):
        
        if round(precip.iloc[row, col], 2) == round(sum(df.iloc[(day*24):((day+1)*24), col]), 2):
            pass
        
        else:
            n_errors += 1
            diff = abs(precip.iloc[row, col] - sum(df.iloc[(day*24):((day+1)*24), col]))
            date_occ = "Year: " + str(year) + "_" + str(year+1) + " | Day: " + str(day) + " | " + precip.columns[col]

            if diff >= 0.01:
                    
                print(date_occ)
                print("Difference:", diff)
                print(" ")

                if diff > max_diff:
                    max_diff = diff
                    max_date_occ = date_occ

                    
print("Number of errors:", n_errors)
print(" ")
print("Maximum difference:", max_diff)
print("Date of occurence:", max_date_occ)

Started water year 1981_1982
Started water year 1982_1983
Started water year 1983_1984
Started water year 1984_1985
Started water year 1985_1986
Started water year 1986_1987
Started water year 1987_1988
Started water year 1988_1989
Started water year 1989_1990
Year: 1989_1990 | Day: 91 | P0000
Difference: 0.015029777288436241

Year: 1989_1990 | Day: 91 | P0002
Difference: 0.011048557758330801

Year: 1989_1990 | Day: 91 | P0003
Difference: 0.010908926725387236

Year: 1989_1990 | Day: 91 | P0004
Difference: 0.02145606994628846

Year: 1989_1990 | Day: 91 | P0005
Difference: 0.02812156319618153

Year: 1989_1990 | Day: 91 | P0006
Difference: 0.029726656675337804

Year: 1989_1990 | Day: 91 | P0009
Difference: 0.013049782514571895

Year: 1989_1990 | Day: 91 | P0010
Difference: 0.01880068182945216

Year: 1989_1990 | Day: 91 | P0011
Difference: 0.02848115324974021

Year: 1989_1990 | Day: 91 | P0012
Difference: 0.036516469717025046

Year: 1989_1990 | Day: 91 | P0013
Difference: 0.044838498830794604

Year: 1989_1990 | Day: 91 | P0014
Difference: 0.051151852607726145

Year: 1989_1990 | Day: 91 | P0017
Difference: 0.015125416517256962

Year: 1989_1990 | Day: 91 | P0018
Difference: 0.016036080121993423

Year: 1989_1990 | Day: 91 | P0019
Difference: 0.023979482650756445

Year: 1989_1990 | Day: 91 | P0020
Difference: 0.021978257894515574

Year: 1989_1990 | Day: 91 | P0021
Difference: 0.033080199956893264

Year: 1989_1990 | Day: 91 | P0022
Difference: 0.04057582378387348

Year: 1989_1990 | Day: 91 | P0028
Difference: 0.012869884967803724

Year: 1989_1990 | Day: 91 | P0029
Difference: 0.024739134311675404

Year: 1989_1990 | Day: 91 | P0030
Difference: 0.02433162212371731

Year: 1989_1990 | Day: 91 | P0031
Difference: 0.03287754058837833

Year: 1989_1990 | Day: 91 | P0032
Difference: 0.042789556980132426

Year: 1989_1990 | Day: 91 | P0033
Difference: 0.035125416517256536

Year: 1989_1990 | Day: 91 | P0034
Difference: 0.029877668619155084

Year: 1989_1990 | Day: 91 | P0035
Difference: 0.023759523630141333

Year: 1989_1990 | Day: 91 | P0037
Difference: 0.010388475656508245

Year: 1989_1990 | Day: 91 | P0042
Difference: 0.011247491836547052

Year: 1989_1990 | Day: 91 | P0043
Difference: 0.013204724788665079

Year: 1989_1990 | Day: 91 | P0044
Difference: 0.021331750154494733

Year: 1989_1990 | Day: 91 | P0045
Difference: 0.03348398685455267

Year: 1989_1990 | Day: 91 | P0046
Difference: 0.04408650279045023

Year: 1989_1990 | Day: 91 | P0047
Difference: 0.04417841672897216

Year: 1989_1990 | Day: 91 | P0052
Difference: 0.011132816076278251

Year: 1989_1990 | Day: 91 | P0053
Difference: 0.016755465269088

Year: 1989_1990 | Day: 91 | P0054
Difference: 0.017897673845290285

Year: 1989_1990 | Day: 91 | P0055
Difference: 0.02612033843994066

Year: 1989_1990 | Day: 91 | P0056
Difference: 0.02091658234596161

Year: 1989_1990 | Day: 91 | P0057
Difference: 0.031059938669203868

Year: 1989_1990 | Day: 91 | P0058
Difference: 0.02306881904601954

Year: 1989_1990 | Day: 91 | P0059
Difference: 0.01695439934730425

Year: 1989_1990 | Day: 91 | P0060
Difference: 0.015999743938445166

Year: 1989_1990 | Day: 91 | P0066
Difference: 0.011941921710966863

Year: 1989_1990 | Day: 91 | P0067
Difference: 0.015136797428129789

Year: 1989_1990 | Day: 91 | P0068
Difference: 0.02124376654624882

Year: 1989_1990 | Day: 91 | P0069
Difference: 0.026954399347304703

Year: 1989_1990 | Day: 91 | P0070
Difference: 0.031203500032424225

Year: 1989_1990 | Day: 91 | P0071
Difference: 0.04595575213432246

Year: 1989_1990 | Day: 91 | P0072
Difference: 0.05399851918220455

Year: 1989_1990 | Day: 91 | P0078
Difference: 0.015477555990218272

Year: 1989_1990 | Day: 91 | P0079
Difference: 0.019183238744735265

Year: 1989_1990 | Day: 91 | P0080
Difference: 0.020692692995070816

Year: 1989_1990 | Day: 91 | P0081
Difference: 0.014478908777236343

Year: 1989_1990 | Day: 91 | P0082
Difference: 0.022932913303374658

Year: 1989_1990 | Day: 91 | P0083
Difference: 0.019965652227400987

Year: 1989_1990 | Day: 91 | P0084
Difference: 0.011427389383315001

Year: 1989_1990 | Day: 91 | P0085
Difference: 0.013399728536604538

Year: 1989_1990 | Day: 91 | P0086
Difference: 0.01157840132713217

Year: 1989_1990 | Day: 91 | P0090
Difference: 0.010260225534437839

Year: 1989_1990 | Day: 91 | P0091
Difference: 0.011350786685942693

Year: 1989_1990 | Day: 91 | P0092
Difference: 0.014362039566039098

Year: 1989_1990 | Day: 91 | P0093
Difference: 0.01892301321029566

Year: 1989_1990 | Day: 91 | P0094
Difference: 0.023766974210738256

Year: 1989_1990 | Day: 91 | P0095
Difference: 0.03682242393493573

Year: 1989_1990 | Day: 91 | P0096
Difference: 0.04349536776542573

Year: 1989_1990 | Day: 91 | P0097
Difference: 0.05568787097930805

Year: 1989_1990 | Day: 91 | P0098
Difference: 0.07897466063499348

Year: 1989_1990 | Day: 91 | P0099
Difference: 0.10107524991035366

Year: 1989_1990 | Day: 91 | P0104
Difference: 0.015018396377562748

Year: 1989_1990 | Day: 91 | P0105
Difference: 0.019230955839156127

Year: 1989_1990 | Day: 91 | P0106
Difference: 0.02827257513999859

Year: 1989_1990 | Day: 91 | P0107
Difference: 0.023065093755720856

Year: 1989_1990 | Day: 91 | P0108
Difference: 0.02598836302757146

Year: 1989_1990 | Day: 91 | P0109
Difference: 0.023571970462798353

Year: 1989_1990 | Day: 91 | P0110
Difference: 0.019234886169432697

Year: 1989_1990 | Day: 91 | P0111
Difference: 0.024490289688109623

Year: 1989_1990 | Day: 91 | P0112
Difference: 0.01043246746063109

Year: 1989_1990 | Day: 91 | P0113
Difference: 0.013455101251601098

Year: 1989_1990 | Day: 91 | P0114
Difference: 0.012357089519499764

Year: 1989_1990 | Day: 91 | P0118
Difference: 0.010443848371504583

Year: 1989_1990 | Day: 91 | P0119
Difference: 0.016514276266097028

Year: 1989_1990 | Day: 91 | P0120
Difference: 0.021031258106231188

Year: 1989_1990 | Day: 91 | P0121
Difference: 0.027241317033766976

Year: 1989_1990 | Day: 91 | P0122
Difference: 0.035324350595473564

Year: 1989_1990 | Day: 91 | P0123
Difference: 0.03943754553794787

Year: 1989_1990 | Day: 91 | P0124
Difference: 0.05131052017211801

Year: 1989_1990 | Day: 91 | P0125
Difference: 0.07427405595779346

Year: 1989_1990 | Day: 91 | P0126
Difference: 0.09586776852607615

Year: 1989_1990 | Day: 91 | P0127
Difference: 0.11901865243911691

Year: 1989_1990 | Day: 91 | P0131
Difference: 0.01634422779083189

Year: 1989_1990 | Day: 91 | P0132
Difference: 0.01918323874473482

Year: 1989_1990 | Day: 91 | P0133
Difference: 0.03201852440833952

Year: 1989_1990 | Day: 91 | P0134
Difference: 0.0323380529880517

Year: 1989_1990 | Day: 91 | P0135
Difference: 0.029051263332366073

Year: 1989_1990 | Day: 91 | P0136
Difference: 0.025764473676680444

Year: 1989_1990 | Day: 91 | P0137
Difference: 0.030748065710067163

Year: 1989_1990 | Day: 91 | P0138
Difference: 0.020660082101820576

Year: 1989_1990 | Day: 91 | P0139
Difference: 0.022125544548033393

Year: 1989_1990 | Day: 91 | P0140
Difference: 0.015328075885771675

Year: 1989_1990 | Day: 91 | P0141
Difference: 0.013547015190123468

Year: 1989_1990 | Day: 91 | P0146
Difference: 0.015559620857237944

Year: 1989_1990 | Day: 91 | P0147
Difference: 0.015555895566939426

Year: 1989_1990 | Day: 91 | P0148
Difference: 0.023143228292464346

Year: 1989_1990 | Day: 91 | P0149
Difference: 0.034692949056624456

Year: 1989_1990 | Day: 91 | P0150
Difference: 0.03779611587524362

Year: 1989_1990 | Day: 91 | P0152
Difference: 0.07491683840751562

Year: 1989_1990 | Day: 91 | P0153
Difference: 0.10066773772239579

Year: 1989_1990 | Day: 91 | P0158
Difference: 0.025018396377562757

Year: 1989_1990 | Day: 91 | P0159
Difference: 0.04767378449439863

Year: 1989_1990 | Day: 91 | P0160
Difference: 0.06808895230293177

Year: 1989_1990 | Day: 91 | P0161
Difference: 0.06599208831787018

Year: 1989_1990 | Day: 91 | P0162
Difference: 0.060468803644179614

Year: 1989_1990 | Day: 91 | P0163
Difference: 0.03873546004295303

Year: 1989_1990 | Day: 91 | P0164
Difference: 0.030604709386825135

Year: 1989_1990 | Day: 91 | P0165
Difference: 0.026043735742567797

Year: 1989_1990 | Day: 91 | P0166
Difference: 0.025272703170775235

Year: 1989_1990 | Day: 91 | P0167
Difference: 0.02002495527267323

Year: 1989_1990 | Day: 91 | P0169
Difference: 0.011490417718886592

Year: 1989_1990 | Day: 91 | P0173
Difference: 0.012408736944197918

Year: 1989_1990 | Day: 91 | P0174
Difference: 0.014972211122512236

Year: 1989_1990 | Day: 91 | P0183
Difference: 0.017195588350295665

Year: 1989_1990 | Day: 91 | P0184
Difference: 0.04862078428268335

Year: 1989_1990 | Day: 91 | P0185
Difference: 0.08935548067092847

Year: 1989_1990 | Day: 91 | P0186
Difference: 0.11648758411407356

Year: 1989_1990 | Day: 91 | P0187
Difference: 0.11110020518302832

Year: 1989_1990 | Day: 91 | P0188
Difference: 0.08799703836440975

Year: 1989_1990 | Day: 91 | P0189
Difference: 0.06333670020103388

Year: 1989_1990 | Day: 91 | P0190
Difference: 0.04968639016151366

Year: 1989_1990 | Day: 91 | P0191
Difference: 0.032202147245406376

Year: 1989_1990 | Day: 91 | P0192
Difference: 0.02988139390945377

Year: 1989_1990 | Day: 91 | P0193
Difference: 0.020660082101820576

Year: 1989_1990 | Day: 91 | P0194
Difference: 0.01628273129463087

Year: 1989_1990 | Day: 91 | P0195
Difference: 0.010528106689452255

Year: 1989_1990 | Day: 91 | P0207
Difference: 0.017004309892653335

Year: 1989_1990 | Day: 91 | P0208
Difference: 0.0720320987701406

Year: 1989_1990 | Day: 91 | P0209
Difference: 0.12551016688346772

Year: 1989_1990 | Day: 91 | P0210
Difference: 0.1702221524715417

Year: 1989_1990 | Day: 91 | P0211
Difference: 0.16465860128402654

Year: 1989_1990 | Day: 91 | P0212
Difference: 0.12930776357650697

Year: 1989_1990 | Day: 91 | P0213
Difference: 0.08396810173988278

Year: 1989_1990 | Day: 91 | P0214
Difference: 0.05721462488174378

Year: 1989_1990 | Day: 91 | P0215
Difference: 0.047493886947631125

Year: 1989_1990 | Day: 91 | P0216
Difference: 0.03740217804908719

Year: 1989_1990 | Day: 91 | P0217
Difference: 0.018875091075896577

Year: 1989_1990 | Day: 91 | P0218
Difference: 0.021890274286268996

Year: 1989_1990 | Day: 91 | P0219
Difference: 0.0164589035511008

Year: 1989_1990 | Day: 91 | P0220
Difference: 0.014824924468993306

Year: 1989_1990 | Day: 91 | P0221
Difference: 0.012500445842742236

Year: 1989_1990 | Day: 91 | P0223
Difference: 0.010172241926192926

Year: 1989_1990 | Day: 91 | P0224
Difference: 0.014105539321898897

Year: 1989_1990 | Day: 91 | P0230
Difference: 0.021716295480727066

Year: 1989_1990 | Day: 91 | P0231
Difference: 0.07664844512939428

Year: 1989_1990 | Day: 91 | P0232
Difference: 0.12519063830375643

Year: 1989_1990 | Day: 91 | P0233
Difference: 0.15478312611579814

Year: 1989_1990 | Day: 91 | P0234
Difference: 0.15802592396736093

Year: 1989_1990 | Day: 91 | P0235
Difference: 0.11921584963798448

Year: 1989_1990 | Day: 91 | P0236
Difference: 0.08971900105476305

Year: 1989_1990 | Day: 91 | P0237
Difference: 0.06259827852249078

Year: 1989_1990 | Day: 91 | P0238
Difference: 0.038724079132079314

Year: 1989_1990 | Day: 91 | P0239
Difference: 0.02982602119445721

Year: 1989_1990 | Day: 91 | P0240
Difference: 0.02092423796653664

Year: 1989_1990 | Day: 91 | P0241
Difference: 0.011523028612135944

Year: 1989_1990 | Day: 91 | P0243
Difference: 0.012907958030699995

Year: 1989_1990 | Day: 91 | P0245
Difference: 0.013642654418945022

Year: 1989_1990 | Day: 91 | P0246
Difference: 0.01136216759681652

Year: 1989_1990 | Day: 91 | P0247
Difference: 0.013738293647765576

Year: 1989_1990 | Day: 91 | P0248
Difference: 0.017847763299941366

Year: 1989_1990 | Day: 91 | P0250
Difference: 0.01492275714874225

Year: 1989_1990 | Day: 91 | P0251
Difference: 0.05839316964149388

Year: 1989_1990 | Day: 91 | P0252
Difference: 0.10377682328224092

Year: 1989_1990 | Day: 91 | P0253
Difference: 0.12208747148513721

Year: 1989_1990 | Day: 91 | P0254
Difference: 0.12345356941223118

Year: 1989_1990 | Day: 91 | P0255
Difference: 0.0949630236625667

Year: 1989_1990 | Day: 91 | P0256
Difference: 0.06802592396736085

Year: 1989_1990 | Day: 91 | P0257
Difference: 0.05191522955894401

Year: 1989_1990 | Day: 91 | P0258
Difference: 0.03973038196563672

Year: 1989_1990 | Day: 91 | P0259
Difference: 0.02494179368019034

Year: 1989_1990 | Day: 91 | P0260
Difference: 0.016363264322279747

Year: 1989_1990 | Day: 91 | P0263
Difference: 0.011310520172118532

Year: 1989_1990 | Day: 91 | P0266
Difference: 0.010818749666213434

Year: 1989_1990 | Day: 91 | P0267
Difference: 0.014744596481322675

Year: 1989_1990 | Day: 91 | P0270
Difference: 0.016623489856719464

Year: 1989_1990 | Day: 91 | P0271
Difference: 0.041551709175108975

Year: 1989_1990 | Day: 91 | P0272
Difference: 0.07789001822471531

Year: 1989_1990 | Day: 91 | P0273
Difference: 0.09473520398139845

Year: 1989_1990 | Day: 91 | P0274
Difference: 0.09696797370910604

Year: 1989_1990 | Day: 91 | P0275
Difference: 0.07103717684745714

Year: 1989_1990 | Day: 91 | P0276
Difference: 0.050449767112731525

Year: 1989_1990 | Day: 91 | P0277
Difference: 0.04086493492126397

Year: 1989_1990 | Day: 91 | P0278
Difference: 0.029686390161513643

Year: 1989_1990 | Day: 91 | P0279
Difference: 0.021431114673613694

Year: 1989_1990 | Day: 91 | P0280
Difference: 0.010935618877409792

Year: 1989_1990 | Day: 91 | P0281
Difference: 0.010667737722396153

Year: 1989_1990 | Day: 91 | P0283
Difference: 0.011953302621840856

Year: 1989_1990 | Day: 91 | P0286
Difference: 0.013378498554229262

Year: 1989_1990 | Day: 91 | P0288
Difference: 0.015387378931044998

Year: 1989_1990 | Day: 91 | P0290
Difference: 0.01958702564239445

Year: 1989_1990 | Day: 91 | P0291
Difference: 0.02999826312065057

Year: 1989_1990 | Day: 91 | P0292
Difference: 0.04784975171089134

Year: 1989_1990 | Day: 91 | P0293
Difference: 0.07085355401039051

Year: 1989_1990 | Day: 91 | P0294
Difference: 0.061312713623046466

Year: 1989_1990 | Day: 91 | P0295
Difference: 0.05017816066741898

Year: 1989_1990 | Day: 91 | P0296
Difference: 0.033516597747802246

Year: 1989_1990 | Day: 91 | P0297
Difference: 0.022202147245406367

Year: 1989_1990 | Day: 91 | P0298
Difference: 0.02001729965209864

Year: 1989_1990 | Day: 91 | P0304
Difference: 0.011182270050048515

Year: 1989_1990 | Day: 91 | P0312
Difference: 0.022781901359557377

Year: 1989_1990 | Day: 91 | P0313
Difference: 0.030541681051253544

Year: 1989_1990 | Day: 91 | P0314
Difference: 0.03917185783386179

Year: 1989_1990 | Day: 91 | P0315
Difference: 0.030956848859786

Year: 1989_1990 | Day: 91 | P0316
Difference: 0.01841220617294237

Year: 1989_1990 | Day: 91 | P0317
Difference: 0.01654316186904814

Year: 1989_1990 | Day: 91 | P0318
Difference: 0.011758298873900674

Year: 1989_1990 | Day: 91 | P0331
Difference: 0.011132816076277807

Year: 1989_1990 | Day: 91 | P0332
Difference: 0.01524601101875267

Year: 1989_1990 | Day: 91 | P0334
Difference: 0.01013789415359434

Year: 1989_1990 | Day: 91 | P0351
Difference: 0.053648573160170576

Year: 1989_1990 | Day: 91 | P0352
Difference: 0.06552154779434116

Year: 1989_1990 | Day: 91 | P0353
Difference: 0.06826119422912535

Year: 1989_1990 | Day: 91 | P0354
Difference: 0.051691340208052994

Year: 1989_1990 | Day: 91 | P0355
Difference: 0.02890770196914616

Year: 1989_1990 | Day: 91 | P0356
Difference: 0.0188599848747244

Year: 1989_1990 | Day: 91 | P0357
Difference: 0.012385770082473213

Year: 1989_1990 | Day: 91 | P0372
Difference: 0.10767378449439935

Year: 1989_1990 | Day: 91 | P0373
Difference: 0.12128010272979606

Year: 1989_1990 | Day: 91 | P0374
Difference: 0.12197060227394019

Year: 1989_1990 | Day: 91 | P0375
Difference: 0.0883568334579461

Year: 1989_1990 | Day: 91 | P0376
Difference: 0.050780676603316754

Year: 1989_1990 | Day: 91 | P0377
Difference: 0.02817693591117809

Year: 1989_1990 | Day: 91 | P0378
Difference: 0.012426036596297818

Year: 1989_1990 | Day: 91 | P0394
Difference: 0.1301455497741688

Year: 1989_1990 | Day: 91 | P0395
Difference: 0.14325244188308628

Year: 1989_1990 | Day: 91 | P0396
Difference: 0.1472260057926169

Year: 1989_1990 | Day: 91 | P0397
Difference: 0.10863609552383369

Year: 1989_1990 | Day: 91 | P0398
Difference: 0.06005363583564716

Year: 1989_1990 | Day: 91 | P0399
Difference: 0.02799703836440992

Year: 1989_1990 | Day: 91 | P0400
Difference: 0.015209674835204634

Year: 1989_1990 | Day: 91 | P0401
Difference: 0.010832324028014595

Year: 1989_1990 | Day: 91 | P0416
Difference: 0.08024118900298993

Year: 1989_1990 | Day: 91 | P0417
Difference: 0.08366760969161913

Year: 1989_1990 | Day: 91 | P0418
Difference: 0.090748065710067

Year: 1989_1990 | Day: 91 | P0419
Difference: 0.060788332223891794

Year: 1989_1990 | Day: 91 | P0420
Difference: 0.03480588793754502

Year: 1989_1990 | Day: 91 | P0421
Difference: 0.014662531614303198

Year: 1989_1990 | Day: 91 | P0437
Difference: 0.031710376739501056

Year: 1989_1990 | Day: 91 | P0438
Difference: 0.03787271857261565

Year: 1989_1990 | Day: 91 | P0439
Difference: 0.028919287919997094

Year: 1989_1990 | Day: 91 | P0440
Difference: 0.02604373574256824

Year: 1989_1990 | Day: 91 | P0441
Difference: 0.014214752912520723

Year: 1989_1990 | Day: 91 | P0457
Difference: 0.011346856355666235

Year: 1989_1990 | Day: 91 | P0501
Difference: 0.014406031370162053

Year: 1989_1990 | Day: 91 | P0522
Difference: 0.016962054967879392

Year: 1989_1990 | Day: 91 | P0906
Difference: 0.019724463224410405

Year: 1989_1990 | Day: 91 | P0907
Difference: 0.017304345369338406

Year: 1989_1990 | Day: 91 | P0908
Difference: 0.020223889350890298

Year: 1989_1990 | Day: 91 | P0909
Difference: 0.01004771709442101

Year: 1989_1990 | Day: 91 | P0924
Difference: 0.015431370735167815

Year: 1989_1990 | Day: 91 | P0925
Difference: 0.03145780682563701

Year: 1989_1990 | Day: 91 | P0926
Difference: 0.03990436077117848

Year: 1989_1990 | Day: 91 | P0941
Difference: 0.020087983608245236

Year: 1989_1990 | Day: 91 | P0942
Difference: 0.043877924680709085

Year: 1989_1990 | Day: 91 | P0943
Difference: 0.06698481678962646

Year: 1989_1990 | Day: 91 | P0957
Difference: 0.01922131180763162

Year: 1989_1990 | Day: 91 | P0958
Difference: 0.027667865753172982

Year: 1989_1990 | Day: 91 | P0959
Difference: 0.04301497817039421

Year: 1989_1990 | Day: 91 | P0973
Difference: 0.01835091471671968

Year: 1989_1990 | Day: 91 | P0974
Difference: 0.015934522151946212

Started water year 1990_1991
Started water year 1991_1992
Started water year 1992_1993
Started water year 1993_1994
Started water year 1994_1995
Started water year 1995_1996
Started water year 1996_1997
Started water year 1997_1998
Started water year 1998_1999
Started water year 1999_2000
Started water year 2000_2001
Started water year 2001_2002
Started water year 2002_2003
Started water year 2003_2004
Started water year 2004_2005
Started water year 2005_2006
Started water year 2006_2007
Started water year 2007_2008
Started water year 2008_2009
Started water year 2009_2010
Started water year 2010_2011
Started water year 2011_2012
Started water year 2012_2013
Started water year 2013_2014
Started water year 2014_2015
Started water year 2015_2016
Started water year 2016_2017
Started water year 2017_2018
Started water year 2018_2019
Started water year 2019_2020
Started water year 2020_2021
Started water year 2021_2022
Year: 2021_2022 | Day: 92 | P0000
Difference: 0.7190667092800139

Year: 2021_2022 | Day: 92 | P0001
Difference: 3.232568502426147

Year: 2021_2022 | Day: 92 | P0002
Difference: 2.6348531246185303

Year: 2021_2022 | Day: 92 | P0003
Difference: 2.021383494138717

Year: 2021_2022 | Day: 92 | P0004
Difference: 1.2031756341457367

Year: 2021_2022 | Day: 92 | P0005
Difference: 0.646773725748062

Year: 2021_2022 | Day: 92 | P0006
Difference: 0.3756694495677947

Year: 2021_2022 | Day: 92 | P0007
Difference: 3.095727413892746

Year: 2021_2022 | Day: 92 | P0008
Difference: 2.7716979384422302

Year: 2021_2022 | Day: 92 | P0009
Difference: 2.177853137254715

Year: 2021_2022 | Day: 92 | P0010
Difference: 1.565936952829361

Year: 2021_2022 | Day: 92 | P0011
Difference: 1.0237321257591245

Year: 2021_2022 | Day: 92 | P0012
Difference: 0.6532259285449981

Year: 2021_2022 | Day: 92 | P0013
Difference: 0.42446330189704873

Year: 2021_2022 | Day: 92 | P0014
Difference: 0.0516399741172789

Year: 2021_2022 | Day: 92 | P0024
Difference: 3.0712001025676727

Year: 2021_2022 | Day: 92 | P0025
Difference: 2.9769577085971832

Year: 2021_2022 | Day: 92 | P0026
Difference: 2.6852004230022426

Year: 2021_2022 | Day: 92 | P0027
Difference: 2.071995288133621

Year: 2021_2022 | Day: 92 | P0028
Difference: 1.4368407428264618

Year: 2021_2022 | Day: 92 | P0029
Difference: 0.8752718567848203

Year: 2021_2022 | Day: 92 | P0030
Difference: 0.5292966961860656

Year: 2021_2022 | Day: 92 | P0031
Difference: 0.415690243244171

Year: 2021_2022 | Day: 92 | P0032
Difference: 0.1858994364738463

Year: 2021_2022 | Day: 92 | P0033
Difference: 0.0503472983837126

Year: 2021_2022 | Day: 92 | P0048
Difference: 2.988576889038086

Year: 2021_2022 | Day: 92 | P0049
Difference: 2.955012023448944

Year: 2021_2022 | Day: 92 | P0050
Difference: 2.83624604344368

Year: 2021_2022 | Day: 92 | P0051
Difference: 2.5793425738811493

Year: 2021_2022 | Day: 92 | P0052
Difference: 1.9222423434257507

Year: 2021_2022 | Day: 92 | P0053
Difference: 1.2444891035556793

Year: 2021_2022 | Day: 92 | P0054
Difference: 0.6958283483982085

Year: 2021_2022 | Day: 92 | P0055
Difference: 0.36017969250679

Year: 2021_2022 | Day: 92 | P0056
Difference: 0.2788491547107695

Year: 2021_2022 | Day: 92 | P0057
Difference: 0.1445896923542021

Year: 2021_2022 | Day: 92 | P0058
Difference: 0.0490583479404448

Year: 2021_2022 | Day: 92 | P0073
Difference: 2.9059574007987976

Year: 2021_2022 | Day: 92 | P0074
Difference: 2.8568990528583527

Year: 2021_2022 | Day: 92 | P0075
Difference: 2.7278028428554535

Year: 2021_2022 | Day: 92 | P0076
Difference: 2.3714974522590633

Year: 2021_2022 | Day: 92 | P0077
Difference: 1.7079450190067291

Year: 2021_2022 | Day: 92 | P0078
Difference: 1.0895729064941404

Year: 2021_2022 | Day: 92 | P0079
Difference: 0.5150958895683286

Year: 2021_2022 | Day: 92 | P0080
Difference: 0.2026818692684172

Year: 2021_2022 | Day: 92 | P0081
Difference: 0.1226402819156645

Year: 2021_2022 | Day: 92 | P0082
Difference: 0.041309744119644005

Year: 2021_2022 | Day: 92 | P0102
Difference: 2.291459590196609

Year: 2021_2022 | Day: 92 | P0103
Difference: 1.833166927099228

Year: 2021_2022 | Day: 92 | P0104
Difference: 1.4510415494441986

Year: 2021_2022 | Day: 92 | P0105
Difference: 1.0146982967853546

Year: 2021_2022 | Day: 92 | P0106
Difference: 0.3898702561855315

Year: 2021_2022 | Day: 92 | P0107
Difference: 0.1497529447078702

Year: 2021_2022 | Day: 92 | P0108
Difference: 0.061966478824615305

Year: 2021_2022 | Day: 92 | P0109
Difference: 0.020656734704971202

Year: 2021_2022 | Day: 92 | P0129
Difference: 1.5749745070934296

Year: 2021_2022 | Day: 92 | P0130
Difference: 1.1812299489974976

Year: 2021_2022 | Day: 92 | P0131
Difference: 0.8946359157562255

Year: 2021_2022 | Day: 92 | P0132
Difference: 0.6196610629558561

Year: 2021_2022 | Day: 92 | P0133
Difference: 0.23624673485755898

Year: 2021_2022 | Day: 92 | P0134
Difference: 0.07745623588562

Year: 2021_2022 | Day: 92 | P0135
Difference: 0.042602419853210304

Year: 2021_2022 | Day: 92 | P0136
Difference: 0.023238360881805302

Year: 2021_2022 | Day: 92 | P0156
Difference: 0.9927488863468168

Year: 2021_2022 | Day: 92 | P0157
Difference: 0.7229410111904142

Year: 2021_2022 | Day: 92 | P0158
Difference: 0.4505477845668791

Year: 2021_2022 | Day: 92 | P0159
Difference: 0.2310834825038909

Year: 2021_2022 | Day: 92 | P0160
Difference: 0.0864937901496886

Year: 2021_2022 | Day: 92 | P0161
Difference: 0.0555105507373809

Year: 2021_2022 | Day: 92 | P0162
Difference: 0.042602419853210304

Year: 2021_2022 | Day: 92 | P0163
Difference: 0.023238360881805302

Year: 2021_2022 | Day: 92 | P0182
Difference: 0.6196610629558562

Year: 2021_2022 | Day: 92 | P0183
Difference: 0.4828199744224547

Year: 2021_2022 | Day: 92 | P0184
Difference: 0.2517364919185637

Year: 2021_2022 | Day: 92 | P0185
Difference: 0.1252219080924986

Year: 2021_2022 | Day: 92 | P0186
Difference: 0.0593848526477812

Year: 2021_2022 | Day: 92 | P0187
Difference: 0.0374391674995421

Year: 2021_2022 | Day: 92 | P0188
Difference: 0.0335648655891417

Year: 2021_2022 | Day: 92 | P0189
Difference: 0.020656734704971202

Year: 2021_2022 | Day: 92 | P0206
Difference: 0.383414328098297

Year: 2021_2022 | Day: 92 | P0207
Difference: 0.2711005508899687

Year: 2021_2022 | Day: 92 | P0208
Difference: 0.1665353775024413

Year: 2021_2022 | Day: 92 | P0209
Difference: 0.0955313444137572

Year: 2021_2022 | Day: 92 | P0210
Difference: 0.0361464917659758

Year: 2021_2022 | Day: 92 | P0211
Difference: 0.011619180440902599

Year: 2021_2022 | Day: 92 | P0212
Difference: 0.011619180440902599

Year: 2021_2022 | Day: 92 | P0213
Difference: 0.011619180440902599

Year: 2021_2022 | Day: 92 | P0230
Difference: 0.1794435083866118

Year: 2021_2022 | Day: 92 | P0231
Difference: 0.1510418951511382

Year: 2021_2022 | Day: 92 | P0232
Difference: 0.0864937901496886

Year: 2021_2022 | Day: 92 | P0233
Difference: 0.0309832394123076

Year: 2021_2022 | Day: 92 | P0250
Difference: 0.1019872725009917

Year: 2021_2022 | Day: 92 | P0251
Difference: 0.1006945967674254

Year: 2021_2022 | Day: 92 | P0252
Difference: 0.0619664788246153

Year: 2021_2022 | Day: 92 | P0253
Difference: 0.0309832394123076

Year: 2021_2022 | Day: 92 | P0270
Difference: 0.020656734704971202

Year: 2021_2022 | Day: 92 | P0271
Difference: 0.0180751085281371

Year: 2021_2022 | Day: 92 | P0272
Difference: 0.0129081308841704

Year: 2021_2022 | Day: 92 | P0290
Difference: 0.011619180440902599

Year: 2021_2022 | Day: 92 | P0310
Difference: 0.0632591545581815

Year: 2021_2022 | Day: 92 | P0311
Difference: 0.0219456851482389

Started water year 2022_2023
Number of errors: 527004

Maximum difference: 3.232568502426147
Date of occurence: Year: 2021_2022 | Day: 92 | P0001