In [1]:
# Importing libraries
import pandas as pd
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns; sns.set()
from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler 
import warnings
warnings.filterwarnings("ignore")
import scipy
from PIL import Image
import statsmodels.api
from itertools import combinations
import time
import datetime
import pickle
import os

In [2]:
# Importing coordinates
local = pd.read_csv(r"C:\Users\joaoa\Desktop\Doutoramento\Professora\Nova pasta\Todos os Pontos (temperatura)\local.cvs")

# Defining parameters
min_corr = 0.9 ##########
Y = range(1950, 2023) # 1950-2023
K = range(2, 7) # 2-7
T = ["no restriction", "9h-9h"]
H = [1,2,4,6,12,24,48,96]

In [3]:
max_precipitations = pd.read_csv(r"D:\Precipitation\by_water_year\max_precipitations_(mm).csv")
max_precipitations

,year,type_of_period,duration,P0000,P0001,P0002,P0003,P0004,P0005,P0006,...,P1047,P1048,P1055,P1056,P1057,P1058,P1059,P1062,P1063,P1064
0,1950_1951,no restriction,1h,8.326463,8.243036,8.805152,9.028085,9.084161,8.476909,7.380027,...,3.436994,3.357664,3.744721,3.943034,3.918417,3.777545,3.583334,4.295899,4.206998,4.134510
1,1950_1951,no restriction,2h,15.106078,16.101751,16.759608,16.780123,16.432732,15.006237,13.470327,...,6.239377,5.898822,7.132474,7.441573,7.321216,7.192655,7.053152,8.147297,7.940779,7.769816
2,1950_1951,no restriction,3h,20.434577,22.103149,22.261806,21.800894,22.388998,21.266129,19.032700,...,7.886067,8.359287,10.383461,10.725383,10.626908,10.405345,10.334227,11.299809,11.242369,11.195865
3,1950_1951,no restriction,4h,23.979615,25.218735,26.281431,26.591893,26.449654,24.742782,22.127772,...,8.817460,9.966318,14.006458,14.470104,13.779424,13.340397,13.321247,14.879042,14.202038,13.961323
4,1950_1951,no restriction,5h,26.202101,28.151052,28.884135,28.930634,28.555889,26.844913,24.644312,...,9.346757,11.343576,16.998954,17.623985,17.085116,16.196122,15.906174,18.063011,17.503629,17.063234
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3353,2022_2023,9h-9h,24h,54.779407,84.152669,78.163899,69.087140,61.068974,52.875238,47.976034,...,33.152206,27.432676,23.512300,24.586378,25.095019,25.851524,27.461352,29.078925,29.064724,29.050523
3354,2022_2023,9h-9h,48h,87.853795,110.887036,107.861828,103.527183,96.785700,88.935407,80.281787,...,38.806304,32.095753,46.217747,48.270375,49.124993,49.509700,50.263621,50.270073,50.356567,50.426278
3355,2022_2023,9h-9h,72h,94.963124,117.144329,117.125774,116.913173,110.899793,101.122091,88.095980,...,38.814284,32.113306,47.071073,49.186960,50.157759,50.774843,51.829558,51.357064,51.497780,51.613968
3356,2022_2023,9h-9h,96h,114.451494,142.719587,142.209170,141.910078,135.120828,124.048291,109.234199,...,45.058457,43.492522,67.695491,71.006805,73.210482,74.905513,76.910375,76.315241,77.277005,78.081276
3357,2022_2023,9h-9h,120h,127.571542,171.079624,161.538120,160.712944,152.890926,139.581149,121.441539,...,46.867097,46.259057,79.192800,83.030829,85.067973,86.424770,88.202422,91.240056,91.855844,92.369648

In [4]:
# Collecting all information in one dictionary
dict_max = {"no restriction" : {}, "9h-9h" : {}}

for t in T: 
    for hours in H:
        dict_max[t][str(hours) + "h"] = max_precipitations[(max_precipitations["type_of_period"] == t) & (max_precipitations["duration"] == str(hours) + "h")].iloc[:, 3:].reset_index(drop = True)

In [5]:
dict_max["no restriction"]["2h"]

,P0000,P0001,P0002,P0003,P0004,P0005,P0006,P0007,P0008,P0009,...,P1047,P1048,P1055,P1056,P1057,P1058,P1059,P1062,P1063,P1064
0,15.106078,16.101751,16.759608,16.780123,16.432732,15.006237,13.470327,14.139125,15.469881,15.907541,...,6.239377,5.898822,7.132474,7.441573,7.321216,7.192655,7.053152,8.147297,7.940779,7.769816
1,12.464751,14.073567,13.534429,12.933630,13.151580,12.666930,11.911271,13.613291,13.914408,13.456997,...,8.812726,8.778032,8.701982,8.625928,8.408446,8.094897,7.755997,8.074198,8.101441,8.125819
2,10.393973,11.455873,11.358475,11.537263,11.692036,11.453206,10.966202,13.035629,14.061667,14.229780,...,8.408070,7.431135,8.295961,8.942734,9.453993,9.854378,10.040402,9.178039,9.502042,9.770606
3,10.587150,14.392886,13.308771,11.773761,11.797167,11.529835,10.704428,15.084011,15.080318,13.484938,...,18.800810,17.942140,9.556249,9.829484,9.716842,9.334290,9.023996,9.459682,9.249277,9.071816
4,11.875100,12.695441,12.615744,12.701819,12.790015,11.994094,11.506323,12.525417,13.038678,12.765575,...,7.126145,7.111683,10.254543,11.699740,12.006845,11.842137,11.392634,9.565946,9.580825,9.593574
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68,15.949108,15.076861,15.967527,16.616875,17.082011,16.784510,15.867133,15.086072,15.694894,16.503586,...,6.901516,6.789032,7.202704,7.175071,7.382311,7.743368,8.784166,7.280074,7.237703,7.202704
69,10.717563,12.638621,11.551566,11.916995,11.875931,11.277262,10.653798,13.386086,13.622321,13.160054,...,4.835457,6.208576,9.888686,11.274729,10.481123,8.687206,8.456506,10.134153,9.026796,8.102152
70,13.299342,15.682004,15.742909,15.191074,14.594946,13.339944,11.520188,15.331339,16.340878,15.894245,...,12.182757,13.332564,16.206149,15.726298,14.534041,12.786269,12.068331,14.004357,13.127699,12.393154
71,12.909448,15.618321,15.616767,15.241096,14.368670,14.112530,12.901690,15.891533,15.610557,15.306296,...,9.502776,8.951534,12.583012,11.494730,10.261860,9.253617,9.207144,6.805956,6.642003,7.383015
72,13.284003,19.012965,16.909637,14.551729,14.275461,13.889465,12.901878,19.292239,18.995412,15.790945,...,8.339915,6.906841,13.289165,13.986288,13.542198,13.111014,12.927696,13.495721,13.077449,12.726307

In [6]:
dict_corr = {"no restriction" : {}, "9h-9h" : {}}

for t in T:
    for h in H:
        df = dict_max[t][str(h) + "h"]

        # Standardizing dataframe
        scaler = StandardScaler() 
        variables = scaler.fit_transform(df) 
        variables = pd.DataFrame(variables, columns = df.columns)
        variables = variables*np.sqrt((len(variables)-1)/len(variables))
        var_list = variables.columns

        reset_columns = []
        for _ in range(0,1012):
            reset_columns.append(str(_))
        variables.columns = reset_columns
        dict_corr[t][str(h) + "h"] = variables.corr()

In [7]:
dict_corr["no restriction"]["1h"]

,0,1,2,3,4,5,6,7,8,9,...,1002,1003,1004,1005,1006,1007,1008,1009,1010,1011
0,1.000000,0.830803,0.863447,0.922671,0.928403,0.943291,0.913526,0.767307,0.798897,0.818998,...,0.012531,0.027630,0.065500,0.038797,0.015650,0.029540,0.078622,-0.025612,-0.020624,-0.013909
1,0.830803,1.000000,0.979711,0.916963,0.806121,0.783459,0.746534,0.959828,0.956247,0.920597,...,0.095652,0.140949,0.211280,0.194189,0.169351,0.144487,0.150213,0.128311,0.126256,0.107652
2,0.863447,0.979711,1.000000,0.960963,0.854304,0.825782,0.794800,0.928555,0.954006,0.950736,...,0.065094,0.096292,0.184180,0.162245,0.145805,0.136955,0.151750,0.094351,0.100013,0.085924
3,0.922671,0.916963,0.960963,1.000000,0.944964,0.911961,0.875830,0.871360,0.907088,0.938444,...,0.065848,0.080874,0.168051,0.148374,0.135360,0.143370,0.166452,0.079138,0.090926,0.090444
4,0.928403,0.806121,0.854304,0.944964,1.000000,0.979201,0.917224,0.769530,0.819718,0.865207,...,0.052339,0.068176,0.133569,0.111862,0.103326,0.125578,0.161940,0.050465,0.068944,0.086747
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1007,0.029540,0.144487,0.136955,0.143370,0.125578,0.110862,0.134356,0.173807,0.154675,0.155767,...,0.536635,0.553357,0.838928,0.857541,0.934469,1.000000,0.941584,0.838760,0.887069,0.912082
1008,0.078622,0.150213,0.151750,0.166452,0.161940,0.145911,0.186576,0.191688,0.177222,0.183860,...,0.499958,0.504073,0.686123,0.713304,0.803581,0.941584,1.000000,0.709827,0.784252,0.840842
1009,-0.025612,0.128311,0.094351,0.079138,0.050465,0.047476,0.053767,0.160194,0.126939,0.106876,...,0.404816,0.411286,0.881820,0.912719,0.920198,0.838760,0.709827,1.000000,0.980251,0.937769
1010,-0.020624,0.126256,0.100013,0.090926,0.068944,0.058229,0.067554,0.164888,0.135171,0.121556,...,0.448291,0.453860,0.851824,0.874145,0.910630,0.887069,0.784252,0.980251,1.000000,0.982868
1011,-0.013909,0.107652,0.085924,0.090444,0.086747,0.069867,0.078154,0.152172,0.120663,0.115260,...,0.478154,0.480968,0.826678,0.840365,0.891560,0.912082,0.840842,0.937769,0.982868,1.000000

In [8]:
# Checking if there is already saved information
if os.path.isfile(r"C:\Users\joaoa\Desktop\docs\dict_resume_9.pkl"): ##########
    
    # Uploading dictionary
    with open(r"C:\Users\joaoa\Desktop\docs\dict_resume_9.pkl", "rb") as h: ##########
        dict_resume = pickle.load(h)
        
    # Reporting resume
    for t in T:
        for n in dict_resume["clusters"][t].keys():
            print("Lenght of dictionary " + str(n) + " (" + t + "):", len(dict_resume["clusters"][t][n]))
        print("Number of rows that are still being considered (" + t + "):", len(dict_resume["rows"][t]))
        
        
else:  
    dict_resume = {"clusters" : {"no restriction" : {}, "9h-9h" : {}}, 
                   "rows" : {"no restriction" : [], "9h-9h" : []}}
    
    # dict_resume["clusters"][n=1]
    for t in T:

        dict_resume["clusters"][t][1] = set()
        for _ in range(0,1012):

            dict_resume["clusters"][t][1].add(tuple([_]))
            dict_resume["rows"][t].append(_)
        print("Lenght of dictionary 1 (" + t + "):", len(dict_resume["clusters"][t][1]), "| Current time:", datetime.datetime.now().time(), "\n")

    # Saving dictionary
    with open(r"C:\Users\joaoa\Desktop\docs\dict_resume_9.pkl", "wb") as h: ##########
        pickle.dump(dict_resume, h)

Lenght of dictionary 1 (no restriction): 1012
Lenght of dictionary 2 (no restriction): 3396
Lenght of dictionary 3 (no restriction): 4014
Lenght of dictionary 4 (no restriction): 2974
Lenght of dictionary 5 (no restriction): 2143
Lenght of dictionary 6 (no restriction): 1522
Lenght of dictionary 7 (no restriction): 951
Lenght of dictionary 8 (no restriction): 462
Lenght of dictionary 9 (no restriction): 156
Lenght of dictionary 10 (no restriction): 32
Lenght of dictionary 11 (no restriction): 3
Lenght of dictionary 12 (no restriction): 0
Number of rows that are still being considered (no restriction): 0
Lenght of dictionary 1 (9h-9h): 1012
Lenght of dictionary 2 (9h-9h): 3381
Lenght of dictionary 3 (9h-9h): 3996
Lenght of dictionary 4 (9h-9h): 3000
Lenght of dictionary 5 (9h-9h): 2177
Lenght of dictionary 6 (9h-9h): 1515
Lenght of dictionary 7 (9h-9h): 930
Lenght of dictionary 8 (9h-9h): 451
Lenght of dictionary 9 (9h-9h): 154
Lenght of dictionary 10 (9h-9h): 32
Lenght of dictionary 11 (9h-9h): 3
Lenght of dictionary 12 (9h-9h): 0
Number of rows that are still being considered (9h-9h): 0

In [9]:
time_consumed = []

# dict_clusters[n>1]
for t in T:

    n = len(dict_resume["clusters"][t])+1
    while len(dict_resume["clusters"][t][n-1]) != 0:
        
        i = time.time()
        i_percent = time.time()
        time_consumed_percent = []
        dict_resume["clusters"][t][n] = set()
        p = 0
        
        for_row_list = dict_resume["rows"][t].copy()
        
        r = 0
        for row in for_row_list:
            
            len_i = len(dict_resume["clusters"][t][n])

            if (100*r) // len(for_row_list) > p:
                p = (100*r) // len(for_row_list)
                time_consumed_percent.append(time.time()-i_percent)
                i_percent = time.time()
                print("Completed", p, "% | Lenght:", len(dict_resume["clusters"][t][n]), "| Current time:", datetime.datetime.now().time(), "| Duration:", round(time_consumed_percent[-1]/60,1), "min")                
            r += 1
                
            for tup in dict_resume["clusters"][t][n-1]:

                if row in tup:
                    continue

                check = 0
                for col in tup:
                    for h in H:
                        if dict_corr[t][str(h) + "h"].iloc[row,col] < min_corr:
                            check = 1
                            break
                    if check == 1:
                        break

                if check == 0:
                    lista = list(tup + (row,))
                    lista.sort()
                    dict_resume["clusters"][t][n].add(tuple(lista))

            if len(dict_resume["clusters"][t][n]) == len_i:
                dict_resume["rows"][t].remove(row)
                
        # Saving dictionary
        with open(r"C:\Users\joaoa\Desktop\docs\dict_resume_9.pkl", "wb") as h: ##########
            pickle.dump(dict_resume, h)
            
        # Time prediction
        time_consumed.append((time.time()-i)/len(dict_resume["clusters"][t][n-1]))
        print("Lenght of dictionary " + str(n) + " (" + t + "):", len(dict_resume["clusters"][t][n]), "| Current time:", datetime.datetime.now().time(), "| Expected next result in", round(np.mean(time_consumed)*len(dict_resume["clusters"][t][n])/60,1), "min", "\n")

        n += 1

In [10]:
dict_resume["clusters"]["no restriction"][11]

{(473, 474, 475, 493, 494, 495, 513, 514, 515, 534, 535),
 (474, 475, 493, 494, 495, 513, 514, 515, 516, 534, 535),
 (474, 475, 494, 495, 496, 514, 515, 516, 534, 535, 536)}